In [ ]:
# 1.Create a NumPy array containing numbers from 10 to 100 with a step of 10
import numpy as np
a= np.arange(10, 101, 10)
print(a)

[ 10  20  30  40  50  60  70  80  90 100]


In [ ]:
# 2.Create a 3 x 4 array of zeros. 
a= np.zeros((3, 4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# 3.Create an array and print its ndim, shape, size, and dtype. 
b=np.array([[1,3,5],[7,9,11]])
print("Original array:")
print(b)
print("Datatype:", b.dtype)
print("Shape:",b.shape)
print("size:", b.size)
print("Dimension:", b.ndim)

Original array:
[[ 1  3  5]
 [ 7  9 11]]
Datatype: int32
Shape: (2, 3)
size: 6
Dimension: 2


In [ ]:
# 4.Extract the last element from a 1D array.
arr1=np.array([1,2,3,4,5])
print(arr1[-1])

5


In [ ]:
# 5.Select the first two columns of a 2D array.
arr2=np.array([[2,4,6],[1,3,5],[1,2,3]])
print("Original array:")
print(arr2)
print("only first 2 columns of array:")
print(arr2[:, :2])

Original array:
[[2 4 6]
 [1 3 5]
 [1 2 3]]
only first 2 columns of array:
[[2 4]
 [1 3]
 [1 2]]


In [ ]:
# 6.Reshape 12 numbers into a 3 × 4 matrix
n=np.arange(1,13)
m=n.reshape(3,4)
print(m)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# 7.Transpose a 2 × 3 matrix
a=np.array([[1,2,3],[4,5,6]])
print("Original:",a)
print("Transpose:",a.T)

Original: [[1 2 3]
 [4 5 6]]
Transpose: [[1 4]
 [2 5]
 [3 6]]


In [ ]:
# 8.Multiply every element by 5
a=np.array([2,4,6,8,5])
print(a)
print("Multiplying array with 5: ",a*5)

[2 4 6 8 5]
Multiplying array with 5:  [10 20 30 40 25]


In [ ]:
# 9.Create feature matrix X with 5 samples and 3 features
X = np.array([[60, 70, 80],[55, 65, 75],[80, 85, 90],[45, 50, 60],[90, 95, 100]])
print("X:")
print(X)
print("Shape:", X.shape)

X:
[[ 60  70  80]
 [ 55  65  75]
 [ 80  85  90]
 [ 45  50  60]
 [ 90  95 100]]
Shape: (5, 3)


In [ ]:
# 10.Mean of each feature using axis=0
mean = np.mean(X, axis=0)
print("Mean of each feature:", mean)

Mean of each feature: [66. 73. 81.]


In [ ]:
# 11.Filter rows where first feature > 50
result = X[X[:, 0] > 50]

print(result)

[[ 60  70  80]
 [ 55  65  75]
 [ 80  85  90]
 [ 90  95 100]]


In [ ]:
# 12.Standardize every feature column
mean = np.mean(X, axis=0)
std = np.std(X, axis=0)
X_standardized = (X - mean) / std

print("Standardization:",X_standardized)
print("Mean:", np.mean(X_standardized, axis=0))
print("Standard deviation:", np.std(X_standardized, axis=0))

Standardization: [[-0.36247326 -0.19127301 -0.07372098]
 [-0.6645343  -0.51006137 -0.44232587]
 [ 0.84577093  0.76509206  0.6634888 ]
 [-1.2686564  -1.46642644 -1.54814054]
 [ 1.44989302  1.40266877  1.40069858]]
Mean: [0.0000000e+00 4.4408921e-17 4.4408921e-17]
Standard deviation: [1. 1. 1.]


In [ ]:
# 13.Random matrix (10, 4) using a fixed seed
np.random.seed(42)
X = np.random.random((10, 4))
print(X)
print("Shape:", X.shape)

[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497 0.18340451]
 [0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184]
 [0.45606998 0.78517596 0.19967378 0.51423444]
 [0.59241457 0.04645041 0.60754485 0.17052412]
 [0.06505159 0.94888554 0.96563203 0.80839735]
 [0.30461377 0.09767211 0.68423303 0.44015249]]
Shape: (10, 4)


In [ ]:
# 14.Calculate X @ weights
X = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9],[2, 4, 6],[3, 6, 9]])
weights = np.array([0.1, 0.2, 0.3])
result = X @ weights
print(result)

[1.4 3.2 5.  2.8 4.2]


In [ ]:
# 15.Add a bias using broadcasting
X = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
weights = np.array([0.1, 0.2, 0.3])
bias = 2
result = X @ weights + bias
print(result)

[3.4 5.2 7. ]


In [ ]:
# 16.Calculate MSE
y_true = np.array([10, 20, 30, 40])
y_pred = np.array([12, 18, 29, 42])
mse = np.mean((y_true - y_pred) ** 2)
print("MSE:", mse)

MSE: 3.25


In [ ]:
# 17.Create a 28 × 28 grayscale image
image = np.zeros((28, 28))
print("Shape:", image.shape)

Shape: (28, 28)


In [ ]:
# 18.Batch of 64 RGB images, 224 × 224
images = np.zeros((64, 224, 224, 3))
print("Shape:", images.shape)

Shape: (64, 224, 224, 3)


In [ ]:
#19. NaN-safe mean  NaN means Not a Number.
arr = np.array([10, 20, np.nan, 40, 50])
print(arr)

[10. 20. nan 40. 50.]


In [51]:
#20. A * B vs A @ B
A = np.array([[1, 2],[3, 4]])
B = np.array([[5, 6],[7, 8]])
print("A * B:")
print(A * B)
print("A@B:")
print(A @ B)

A * B:
[[ 5 12]
 [21 32]]
A@B:
[[19 22]
 [43 50]]
